ENIGMA_PATCH = true

--[[
Add this at the start of all cards that use custom functions
if not ENIGMA_PATCH then Duel.LoadScript("enigma_utility.lua") end
]]

--------------------------------------------
-- Import constants
--------------------------------------------

if not ENIGMA_CONSTANTS_IMPORTED then Duel.LoadScript("enigma_constant.lua") end

if not VORTEX_IMPORTED then Duel.LoadScript("proc_vortex.lua") end

--------------------------------------------
local ATTRIBUTES = {}
ATTRIBUTES[ATTRIBUTE_EARTH] = "EARTH"
ATTRIBUTES[ATTRIBUTE_WATER] = "WATER"
ATTRIBUTES[ATTRIBUTE_FIRE] = "FIRE"
ATTRIBUTES[ATTRIBUTE_WIND] = "WIND"
ATTRIBUTES[ATTRIBUTE_LIGHT] = "LIGHT"
ATTRIBUTES[ATTRIBUTE_DARK] = "DARK"
ATTRIBUTES[ATTRIBUTE_DIVINE] = "DIVINE"
function Auxiliary.DecodeAttribute(attr)
    local out
    for k,v in pairs(ATTRIBUTES) do
        if k&attr==k then
            if out then out = out.."|"..v
            else out = v end
        end
    end
    return out or "NONE"
end

local RACES = {}
RACES[RACE_WARRIOR] = "WARRIOR"
RACES[RACE_SPELLCASTER] = "SPELLCASTER"
RACES[RACE_FAIRY] = "FAIRY"
RACES[RACE_FIEND] = "FIEND"
RACES[RACE_ZOMBIE] = "ZOMBIE"
RACES[RACE_MACHINE] = "MACHINE"
RACES[RACE_AQUA] = "AQUA"
RACES[RACE_PYRO] = "PYRO"
RACES[RACE_ROCK] = "ROCK"
RACES[RACE_WINGEDBEAST] = "WINGEDBEAST"
RACES[RACE_PLANT] = "PLANT"
RACES[RACE_INSECT] = "INSECT"
RACES[RACE_THUNDER] = "THUNDER"
RACES[RACE_DRAGON] = "DRAGON"
RACES[RACE_BEAST] = "BEAST"
RACES[RACE_BEASTWARRIOR] = "BEASTWARRIOR"
RACES[RACE_DINOSAUR] = "DINOSAUR"
RACES[RACE_FISH] = "FISH"
RACES[RACE_SEASERPENT] = "SEASERPENT"
RACES[RACE_REPTILE] = "REPTILE"
RACES[RACE_PSYCHIC] = "PSYCHIC"
RACES[RACE_DIVINE] = "DIVINE"
RACES[RACE_CREATORGOD] = "CREATORGOD"
RACES[RACE_WYRM] = "WYRM"
RACES[RACE_CYBERSE] = "CYBERSE"
RACES[RACE_ILLUSION] = "ILLUSION"
RACES[RACE_CYBORG] = "CYBORG"
RACES[RACE_MAGICALKNIGHT] = "MAGICALKNIGHT"
RACES[RACE_HIGHDRAGON] = "HIGHDRAGON"
RACES[RACE_OMEGAPSYCHIC] = "OMEGAPSYCHIC"
RACES[RACE_CELESTIALWARRIOR] = "CELESTIALWARRIOR"
RACES[RACE_GALAXY] = "GALAXY"
RACES[RACE_YOKAI] = "YOKAI"
function Auxiliary.DecodeRace(race)
    local out
    for k,v in pairs(RACES) do
        if k&race==k then
            if out then out = out.."|"..v
            else out = v end
        end
    end
    return out or "NONE"
end

local REASONS = {}
REASONS[REASON_DESTROY] = "DESTROY"
REASONS[REASON_RELEASE] = "RELEASE"
REASONS[REASON_TEMPORARY] = "TEMPORARY"
REASONS[REASON_MATERIAL] = "MATERIAL"
REASONS[REASON_SUMMON] = "SUMMON"
REASONS[REASON_BATTLE] = "BATTLE"
REASONS[REASON_EFFECT] = "EFFECT"
REASONS[REASON_COST] = "COST"
REASONS[REASON_ADJUST] = "ADJUST"
REASONS[REASON_LOST_TARGET] = "LOST_TARGET"
REASONS[REASON_RULE] = "RULE"
REASONS[REASON_SPSUMMON] = "SPSUMMON"
REASONS[REASON_DISSUMMON] = "DISSUMMON"
REASONS[REASON_FLIP] = "FLIP"
REASONS[REASON_DISCARD] = "DISCARD"
REASONS[REASON_RDAMAGE] = "RDAMAGE"
REASONS[REASON_RRECOVER] = "RRECOVER"
REASONS[REASON_RETURN] = "RETURN"
REASONS[REASON_FUSION] = "FUSION"
REASONS[REASON_SYNCHRO] = "SYNCHRO"
REASONS[REASON_RITUAL] = "RITUAL"
REASONS[REASON_XYZ] = "XYZ"
REASONS[REASON_REPLACE] = "REPLACE"
REASONS[REASON_DRAW] = "DRAW"
REASONS[REASON_REDIRECT] = "REDIRECT"
REASONS[REASON_EXCAVATE] = "EXCAVATE"
REASONS[REASON_LINK] = "LINK"
REASONS[REASON_REVEAL] = "REVEAL"
function Auxiliary.DecodeReason(reason)
    local out
    for k,v in pairs(REASONS) do
        if k&reason==k then
            if out then out = out.."|"..v
            else out = v end
        end
    end
    return out or "NONE"
end

local SUMMON_TYPES = {}
SUMMON_TYPES[SUMMON_TYPE_NORMAL] = "NORMAL"
SUMMON_TYPES[SUMMON_TYPE_TRIBUTE] = "TRIBUTE"
SUMMON_TYPES[SUMMON_TYPE_GEMINI] = "GEMINI"
SUMMON_TYPES[SUMMON_TYPE_FLIP] = "FLIP"
SUMMON_TYPES[SUMMON_TYPE_SPECIAL] = "SPECIAL"
SUMMON_TYPES[SUMMON_TYPE_FUSION] = "FUSION"
SUMMON_TYPES[SUMMON_TYPE_RITUAL] = "RITUAL"
SUMMON_TYPES[SUMMON_TYPE_SYNCHRO] = "SYNCHRO"
SUMMON_TYPES[SUMMON_TYPE_XYZ] = "XYZ"
SUMMON_TYPES[SUMMON_TYPE_PENDULUM] = "PENDULUM"
SUMMON_TYPES[SUMMON_TYPE_LINK] = "LINK"
SUMMON_TYPES[SUMMON_TYPE_MAXIMUM] = "MAXIMUM"
SUMMON_TYPES[SUMMON_TYPE_VORTEX] = "VORTEX"
function Auxiliary.DecodeSummonType(summon)
    local out
    for k,v in pairs(SUMMON_TYPES) do
        if k&summon==k then
            if out then out = out.."|"..v
            else out = v end
        end
    end
    return out or "NONE"
end

local EVENTS = {}
EVENTS[EVENT_STARTUP] = "STARTUP"
EVENTS[EVENT_FLIP] = "FLIP"
EVENTS[EVENT_FREE_CHAIN] = "FREE_CHAIN"
EVENTS[EVENT_DESTROY] = "DESTROY"
EVENTS[EVENT_REMOVE] = "REMOVE"
EVENTS[EVENT_TO_HAND] = "TO_HAND"
EVENTS[EVENT_TO_DECK] = "TO_DECK"
EVENTS[EVENT_TO_GRAVE] = "TO_GRAVE"
EVENTS[EVENT_LEAVE_FIELD] = "LEAVE_FIELD"
EVENTS[EVENT_CHANGE_POS] = "CHANGE_POS"
EVENTS[EVENT_RELEASE] = "RELEASE"
EVENTS[EVENT_DISCARD] = "DISCARD"
EVENTS[EVENT_LEAVE_FIELD_P] = "LEAVE_FIELD_P"
EVENTS[EVENT_CHAIN_SOLVING] = "CHAIN_SOLVING"
EVENTS[EVENT_CHAIN_ACTIVATING] = "CHAIN_ACTIVATING"
EVENTS[EVENT_CHAIN_SOLVED] = "CHAIN_SOLVED"
EVENTS[EVENT_CHAIN_NEGATED] = "CHAIN_NEGATED"
EVENTS[EVENT_CHAIN_DISABLED] = "CHAIN_DISABLED"
EVENTS[EVENT_CHAIN_END] = "CHAIN_END"
EVENTS[EVENT_CHAINING] = "CHAINING"
EVENTS[EVENT_BECOME_TARGET] = "BECOME_TARGET"
EVENTS[EVENT_DESTROYED] = "DESTROYED"
EVENTS[EVENT_MOVE] = "MOVE"
EVENTS[EVENT_LEAVE_GRAVE] = "LEAVE_GRAVE"
EVENTS[EVENT_ADJUST] = "ADJUST"
EVENTS[EVENT_BREAK_EFFECT] = "BREAK_EFFECT"
EVENTS[EVENT_SUMMON_SUCCESS] = "SUMMON_SUCCESS"
EVENTS[EVENT_FLIP_SUMMON_SUCCESS] = "FLIP_SUMMON_SUCCESS"
EVENTS[EVENT_SPSUMMON_SUCCESS] = "SPSUMMON_SUCCESS"
EVENTS[EVENT_SUMMON] = "SUMMON"
EVENTS[EVENT_FLIP_SUMMON] = "FLIP_SUMMON"
EVENTS[EVENT_SPSUMMON] = "SPSUMMON"
EVENTS[EVENT_MSET] = "MSET"
EVENTS[EVENT_SSET] = "SSET"
EVENTS[EVENT_BE_MATERIAL] = "BE_MATERIAL"
EVENTS[EVENT_BE_PRE_MATERIAL] = "BE_PRE_MATERIAL"
EVENTS[EVENT_DRAW] = "DRAW"
EVENTS[EVENT_DAMAGE] = "DAMAGE"
EVENTS[EVENT_RECOVER] = "RECOVER"
EVENTS[EVENT_PREDRAW] = "PREDRAW"
EVENTS[EVENT_SUMMON_NEGATED] = "SUMMON_NEGATED"
EVENTS[EVENT_FLIP_SUMMON_NEGATED] = "FLIP_SUMMON_NEGATED"
EVENTS[EVENT_SPSUMMON_NEGATED] = "SPSUMMON_NEGATED"
EVENTS[EVENT_CONTROL_CHANGED] = "CONTROL_CHANGED"
EVENTS[EVENT_EQUIP] = "EQUIP"
EVENTS[EVENT_ATTACK_ANNOUNCE] = "ATTACK_ANNOUNCE"
EVENTS[EVENT_BE_BATTLE_TARGET] = "BE_BATTLE_TARGET"
EVENTS[EVENT_BATTLE_START] = "BATTLE_START"
EVENTS[EVENT_BATTLE_CONFIRM] = "BATTLE_CONFIRM"
EVENTS[EVENT_PRE_DAMAGE_CALCULATE] = "PRE_DAMAGE_CALCULATE"
EVENTS[EVENT_DAMAGE_CALCULATING] = "DAMAGE_CALCULATING"
EVENTS[EVENT_PRE_BATTLE_DAMAGE] = "PRE_BATTLE_DAMAGE"
EVENTS[EVENT_BATTLE_END] = "BATTLE_END"
EVENTS[EVENT_BATTLED] = "BATTLED"
EVENTS[EVENT_BATTLE_DESTROYING] = "BATTLE_DESTROYING"
EVENTS[EVENT_BATTLE_DESTROYED] = "BATTLE_DESTROYED"
EVENTS[EVENT_DAMAGE_STEP_END] = "DAMAGE_STEP_END"
EVENTS[EVENT_ATTACK_DISABLED] = "ATTACK_DISABLED"
EVENTS[EVENT_BATTLE_DAMAGE] = "BATTLE_DAMAGE"
EVENTS[EVENT_TOSS_DICE] = "TOSS_DICE"
EVENTS[EVENT_TOSS_COIN] = "TOSS_COIN"
EVENTS[EVENT_TOSS_COIN_NEGATE] = "TOSS_COIN_NEGATE"
EVENTS[EVENT_TOSS_DICE_NEGATE] = "TOSS_DICE_NEGATE"
EVENTS[EVENT_LEVEL_UP] = "LEVEL_UP"
EVENTS[EVENT_PAY_LPCOST] = "PAY_LPCOST"
EVENTS[EVENT_DETACH_MATERIAL] = "DETACH_MATERIAL"
EVENTS[EVENT_TURN_END] = "TURN_END"
EVENTS[EVENT_PHASE] = "PHASE"
EVENTS[EVENT_PHASE_START] = "PHASE_START"
EVENTS[EVENT_ADD_COUNTER] = "ADD_COUNTER"
EVENTS[EVENT_REMOVE_COUNTER] = "REMOVE_COUNTER"
EVENTS[EVENT_CUSTOM] = "CUSTOM"
EVENTS[EVENT_CONFIRM] = "CONFIRM"
EVENTS[EVENT_TOHAND_CONFIRM] = "TOHAND_CONFIRM"
function Auxiliary.DecodeEvent(event)
    local out
    for k,v in pairs(EVENTS) do
        if event==k then
            if out then out = out.."|"..v
            else out = v end
        end
    end
    return out or "NONE"
end

local LOCATIONS = {}
LOCATIONS[LOCATION_DECK] = "DECK"
LOCATIONS[LOCATION_HAND] = "HAND"
LOCATIONS[LOCATION_MZONE] = "MZONE"
LOCATIONS[LOCATION_SZONE] = "SZONE"
LOCATIONS[LOCATION_GRAVE] = "GRAVE"
LOCATIONS[LOCATION_REMOVED] = "REMOVED"
LOCATIONS[LOCATION_EXTRA] = "EXTRA"
LOCATIONS[LOCATION_OVERLAY] = "OVERLAY"
LOCATIONS[LOCATION_ONFIELD] = "ONFIELD"
LOCATIONS[LOCATION_PUBLIC] = "PUBLIC"
function Auxiliary.DecodeLocation(location)
    if not location or type(location) ~= "number" then return "NONE" end -- Tambahkan baris pengaman ini
    local out
    for k,v in pairs(LOCATIONS) do
        if (k & location) == k then 
            if out then out = out.."|"..v
            else out = v end
        end
    end
    return out or "NONE"
end

function Duel.RegisterFlagEffectCustom(player, code, reset_flag, property, reset_count, label)
    if not label then label = 0 end
    Debug.Message("Duel.RegisterFlagEffect("..code..")")
    Duel.RegisterFlagEffect(player, code, reset_flag, property, reset_count, label)
end

function Card.RegisterFlagEffectCustom(c, code, reset_flag, property, reset_count, label, desc)
    if not c or not code then return end 
    Duel.RegisterFlagEffect(c:GetControler(), code, reset_flag, property, reset_count, label)
end


--------------------------------------------
